// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jn-lp/se-lab3/server/plants"
)

// Injectors from modules.go:

func ComposeApiServer(port HttpPortNumber) (*PlantsApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := plants.NewStore(db)
	httpHandlerFunc := plants.HTTPHandler(store)
	plantsApiServer := &PlantsApiServer{
		Port:          port,
		PlantsHandler: httpHandlerFunc,
	}
	return plantsApiServer, nil
}
